# Generated by Django 6.0.3 on 2026-04-08 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_waste_complaint_collector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection_schedule',
            name='area',
        ),
        migrations.AddField(
            model_name='collection_schedule',
            name='collector',
            field=models.ForeignKey(limit_choices_to={'role': 'collector'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection_schedule',
            name='district',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection_schedule',
            name='panchayath',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection_schedule',
            name='ward',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
