# Generated by Django 6.0.3 on 2026-04-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_waste_request_collector_waste_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste_complaint',
            name='category',
        ),
    ]
