# Generated by Django 6.0.3 on 2026-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_remove_collection_schedule_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_schedule',
            name='district',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='collection_schedule',
            name='panchayath',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='collection_schedule',
            name='ward',
            field=models.CharField(),
        ),
    ]
