# Generated by Django 6.0.3 on 2026-04-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverification'),
        ('waste', '0004_alter_collection_schedule_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_schedule',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.district'),
        ),
        migrations.AlterField(
            model_name='collection_schedule',
            name='panchayath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.panchayath'),
        ),
        migrations.AlterField(
            model_name='collection_schedule',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ward'),
        ),
    ]
