# Generated by Django 6.0.3 on 2026-04-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_alter_collection_schedule_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_schedule',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
