# Generated by Django 6.0.3 on 2026-04-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_collection_schedule_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection_schedule',
            name='address',
        ),
    ]
